# Generated by Django 3.2.12 on 2024-02-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('subjects', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='gallery')),
                ('phonenumber', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('zipcode', models.PositiveIntegerField()),
            ],
        ),
    ]
