# Generated by Django 3.2.12 on 2024-02-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rollnumber', models.IntegerField()),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
